[package]
name = "cursive-reactive"
version = "0.1.0"
authors = ["dev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.13.0"

[dev-dependencies]
insta = "0.12.0"
crossbeam = "=0.7.2"
